//! Configuration module for OpenBio
//! 
//! Configuration is stored in the user's app data directory and generated
//! by the Setup Wizard on first launch. The developer never touches user config.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Deployment mode for the application
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum DeploymentMode {
    /// Not configured yet - show Setup Wizard
    #[default]
    Unconfigured,
    /// Solo mode - single user, embedded SQLite
    Local,
    /// Hub mode - hosts a lab server on LAN
    Hub,
    /// Spoke mode - connects to a Hub on LAN
    Spoke,
    /// Enterprise mode - connects to remote API
    Enterprise,
}

/// Main configuration structure
/// This is generated by the Setup Wizard, not by developers
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Config {
    /// Deployment mode (set by Setup Wizard)
    pub mode: DeploymentMode,
    
    /// API URL (for spoke/enterprise modes, set by wizard)
    pub api_url: Option<String>,
    
    /// Local server port (for local/hub modes)
    pub server_port: u16,
    
    /// Lab name (for hub mode - what appears in mDNS discovery)
    pub lab_name: Option<String>,
    
    /// Data directory path (where SQLite and files are stored)
    /// This is relative to app data dir, set by wizard
    pub data_path: String,
}

impl Config {
    /// Create a new unconfigured config (triggers Setup Wizard)
    pub fn new_unconfigured() -> Self {
        Self {
            mode: DeploymentMode::Unconfigured,
            api_url: None,
            server_port: 3000,
            lab_name: None,
            data_path: "data".to_string(),
        }
    }

    /// Get the config file path in user's app data directory
    pub fn config_path() -> PathBuf {
        // Platform-specific app data directory
        // macOS: ~/Library/Application Support/OpenBio/config.toml
        // Windows: %APPDATA%/OpenBio/config.toml
        // Linux: ~/.local/share/OpenBio/config.toml
        let app_dir = dirs::data_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("OpenBio");
        
        app_dir.join("config.toml")
    }

    /// Get the data directory path (for SQLite, files, etc.)
    pub fn data_dir(&self) -> PathBuf {
        let app_dir = dirs::data_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("OpenBio");
        
        app_dir.join(&self.data_path)
    }

    /// Get the SQLite database URL
    pub fn database_url(&self) -> String {
        let db_path = self.data_dir().join("openbio.db");
        format!("file:{}", db_path.display())
    }

    /// Check if config exists (user has completed Setup Wizard)
    pub fn exists() -> bool {
        Self::config_path().exists()
    }

    /// Load configuration from app data directory
    pub fn load() -> Result<Self, crate::Error> {
        let path = Self::config_path();
        
        if !path.exists() {
            // No config = first launch, return unconfigured
            return Ok(Self::new_unconfigured());
        }
        
        let content = std::fs::read_to_string(&path)?;
        let config: Config = toml::from_str(&content)?;
        Ok(config)
    }

    /// Save configuration to app data directory
    /// Called by Setup Wizard when user completes setup
    pub fn save(&self) -> Result<(), crate::Error> {
        let path = Self::config_path();
        
        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        
        let content = toml::to_string_pretty(self)
            .map_err(|e| crate::Error::Storage(e.to_string()))?;
        std::fs::write(&path, content)?;
        Ok(())
    }

    /// Check if app needs to show Setup Wizard
    pub fn needs_setup(&self) -> bool {
        self.mode == DeploymentMode::Unconfigured
    }
}
